# Generated by Django 5.0.6 on 2024-09-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_post_yazar"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="Yazım Tarihi"),
        ),
    ]
