# Generated by Django 5.0.6 on 2024-09-10 15:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_post_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="image",
        ),
    ]
