# Generated by Django 5.0.6 on 2024-09-10 18:18

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_remove_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="İçerik"),
        ),
        migrations.AlterField(
            model_name="post",
            name="source",
            field=django_ckeditor_5.fields.CKEditor5Field(
                default="", verbose_name="Kaynakça"
            ),
        ),
    ]
