# Generated by Django 5.0.6 on 2024-09-12 14:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_content_alter_post_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Kaynakça'),
        ),
    ]
