# Generated by Django 5.0.6 on 2024-10-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0006_alter_post_content_alter_post_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="images",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Derginin Kapağı"
            ),
        ),
    ]
