# Generated by Django 5.0.6 on 2024-10-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0008_remove_post_images_post_descriptionone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="descriptionOne",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Ek 1 Açıklama"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="descriptionThree",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Ek 1 Açıklama"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="descriptionTwo",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Ek 1 Açıklama"
            ),
        ),
    ]
