# Generated by Django 5.0.6 on 2024-06-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_article_image_alter_article_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.FileField(blank=True, null=True, upload_to='media', verbose_name='makaleye Fotoğraf Ekle'),
        ),
    ]
