# Generated by Django 5.0.6 on 2024-06-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.FileField(blank=True, null=True, upload_to='articles/', verbose_name='makaleye Fotoğraf Ekle'),
        ),
    ]
