# Generated by Django 5.0.6 on 2024-06-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_article_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, null=True, upload_to='article/', verbose_name='makaleye Fotoğraf Ekle'),
        ),
    ]
