# Generated by Django 5.0.6 on 2024-06-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_rename_article_image_article_article_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publisher',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Yayıncı İsmi'),
        ),
    ]
