# Generated by Django 5.0.6 on 2024-06-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_alter_article_article_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_language',
            field=models.CharField(choices=[('EN', 'İngilizce'), ('ES', 'İspanyolca'), ('FR', 'Fransıca'), ('DE', 'Almanca'), ('TR', 'Türkçe')], default='TR', max_length=2, verbose_name='Makale Dili'),
        ),
    ]
