# Generated by Django 5.0.6 on 2024-06-21 17:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=50, null=True, verbose_name='Yayımcı')),
                ('ıssn', models.CharField(blank=True, max_length=100, null=True, verbose_name='ISSN')),
                ('e_ıssn', models.CharField(blank=True, max_length=100, null=True, verbose_name='e-ISSN')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Derginin Kapağı')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Dergi')),
                ('title', models.CharField(max_length=150, verbose_name='Derginin İsmi')),
                ('about', ckeditor.fields.RichTextField(verbose_name='Hakkında')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('first_create', models.DateField(verbose_name='İlk Çıkış Tarihi')),
            ],
        ),
    ]
