# Generated by Django 5.0.6 on 2024-09-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=25, verbose_name="İsim")),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="Soyisim"
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=20, verbose_name="Kullanıcı Adı"),
                ),
                ("password", models.CharField(max_length=40, verbose_name="Parola")),
                (
                    "confirm",
                    models.CharField(max_length=40, verbose_name="Parolayı Onayla"),
                ),
                ("email", models.EmailField(max_length=60, verbose_name="Email")),
                ("birth_date", models.DateField()),
            ],
        ),
    ]
